'use strict';

const {loadCanonicalCatalogs,deepFreeze}=require('./catalogs');
const {NUMBER_WORDS,extractPartySize,detectMissingItem}=require('../engine/classifier');
const {assertFeature}=require('./feature-flags');
const {legacyProjection}=require('./migration');
const {foodSafetyPolicy,abuseReview}=require('./policies');

function normalizeText(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();}
const RULES=Object.freeze([
  ['occurrence.health_symptom',/\b(vomito|vomitei|diarreia|febre|mal estar|passando mal|duas pessoas|mais pessoas)\b/,'health.incident.create','critical','E4','A1'],
  ['occurrence.allergen',/\b(alergia|alergico|reacao alergica|alergeno)\b/,'health.incident.create','serious','E3','A1'],
  ['occurrence.foreign_body',/\b(cabelo|corpo estranho|objeto|plastico|vidro)\b/,'health.incident.create','serious','E3','A1'],
  ['occurrence.quality',/\b(improprio|cheiro estranho|estragado|azedo|frescor)\b/,'health.incident.create','serious','E3','A1'],
  ['occurrence.personalization_ignored',/\b(personalizacao|sem cebola|sem molho|observacao ignorada)\b/,'occurrence.create','sensitive','E2','A1'],
  ['occurrence.wrong_quantity',/\b(quantidade errada|vieram? menos|faltaram dois|duas unidades)\b/,'occurrence.create','sensitive','E2','A1'],
  ['occurrence.wrong_item',/\b(item errado|veio trocado|produto errado)\b/,'occurrence.create','sensitive','E2','A1'],
  ['privacy.opt_out',/\b(nao quero receber|pare de enviar|remover comunicacoes|opt out)\b/,'occurrence.update','low','E0','A1'],
  ['order.status',/\b(status|onde esta|acompanhar pedido|saiu para entrega)\b/,'order.status.read','operational','E1','A0'],
  ['information.menu',/\b(cardapio|menu)\b/,'menu.read','low','E0','A0'],
  ['information.hours',/\b(horario|abre|fecha|funcionamento)\b/,'information.unit.read','low','E0','A0'],
  ['information.address',/\b(endereco|localizacao|onde fica)\b/,'information.unit.read','low','E0','A0']
]);

function extractPartyCandidates(content){const text=normalizeText(content);const numberToken=`(?:\\d{1,2}|${Object.keys(NUMBER_WORDS).join('|')})`;const patterns=[new RegExp(`\\b(?:somos|estamos\\s+em|estaremos\\s+em)\\s+(${numberToken})\\b`,'g'),new RegExp(`\\bmesa\\s+(?:para|de)\\s+(${numberToken})\\b`,'g'),new RegExp(`\\bgrupo\\s+(?:de|com)\\s+(${numberToken})\\b`,'g'),new RegExp(`\\b(${numberToken})\\s+(?:pessoa|pessoas|lugares)\\b`,'g')];const values=[];for(const pattern of patterns)for(const match of text.matchAll(pattern)){const token=match[1];const value=/^\d+$/.test(token)?Number(token):NUMBER_WORDS[token];if(Number.isInteger(value)&&value>0&&!values.includes(value))values.push(value);}return values;}

class NativeConversationEngine{
  constructor(options={}){this.flags=options.flags;this.catalogs=options.catalogs||loadCanonicalCatalogs();this.intentById=new Map(this.catalogs.intents.intents.map((item)=>[item.id,item]));this.scenarioById=new Map(this.catalogs.scenarios.scenarios.map((item)=>[item.scenario_id,item]));this.scenariosByInput=new Map();for(const scenario of this.catalogs.scenarios.scenarios){const key=normalizeText(scenario.input);if(!this.scenariosByInput.has(key))this.scenariosByInput.set(key,[]);this.scenariosByInput.get(key).push(scenario);}}
  fromScenario(scenario){const intent=this.intentById.get(scenario.intent);return this.finish({intent:scenario.intent,subintent:scenario.intent.split('.').slice(1).join('.'),entities:scenario.entities,origin:scenario.origin,severity:scenario.severity,fields_missing:scenario.fields_missing,capability_id:scenario.capability_required,capability_state:scenario.capability_state,authority:scenario.authority,policy_id:`policy:${scenario.intent}`,escalation:scenario.escalation,ideal_response:scenario.ideal_response,prohibited_responses:scenario.prohibited_responses,closure:scenario.closure,expected_result:scenario.expected_result,action:scenario.action,legacy_blocks:intent.legacy_blocks,scenario_id:scenario.scenario_id,basis_classifications:scenario.basis_classifications,confidence:1});}
  analyze(input){assertFeature(this.flags,'conversationEngineV1');const content=String(input.content||'');const context=input.context||{};const scenario=context.scenario_id?this.scenarioById.get(context.scenario_id):null;if(scenario)return this.fromScenario(scenario);const exact=this.scenariosByInput.get(normalizeText(content));if(exact?.length===1)return this.fromScenario(exact[0]);const candidates=extractPartyCandidates(content);if(candidates.length>1&&candidates.some((value)=>value>8)){const intent=this.intentById.get('reservation.large_group');return this.finish({intent:'reservation.large_group',subintent:'large_group',entities:{party_size:{value:null,state:'conflict',candidates,provenance:'message'}},origin:'dining_room',severity:'operational',fields_missing:['party_size','customer_name','arrival_estimate'],capability_id:'human.queue.create',capability_state:'requires_human',authority:'A1',policy_id:'LARGE_GROUP_POLICY',escalation:'E1',ideal_response:'Entendi que é um grupo, mas recebi quantidades diferentes. Qual é a quantidade correta?',prohibited_responses:['escolher quantidade automaticamente'],closure:{expected_state:'open',blocked_by:['party_size:conflict']},expected_result:{status:'requires_human'},action:'clarify_party_size',legacy_blocks:intent.legacy_blocks,scenario_id:null,basis_classifications:['CANÔNICO_INTERNO'],confidence:.7});}const party=extractPartySize(content);if(party.value>8){const intent=this.intentById.get('reservation.large_group');const known=new Set(Object.keys(context).filter((key)=>context[key]!=null&&context[key]!==''));known.add('party_size');const missing=['customer_name','arrival_estimate'].filter((field)=>!known.has(field));return this.finish({intent:'reservation.large_group',subintent:'large_group',entities:{party_size:{value:party.value,state:'provided',provenance:'message'}},origin:'dining_room',severity:'operational',fields_missing:missing,capability_id:'waitlist.create',capability_state:'unknown',authority:'A2',policy_id:'LARGE_GROUP_POLICY',escalation:'E1',ideal_response:`Perfeito. Como são ${party.value} pessoas, vou preparar o atendimento específico.`,prohibited_responses:['confirmar fila sem resultado confirmed'],closure:{expected_state:'open',blocked_by:['human_confirmation']},expected_result:{status:'unknown'},action:'register_large_group',legacy_blocks:intent.legacy_blocks,scenario_id:null,basis_classifications:['CANÔNICO_INTERNO'],confidence:party.confidence});}
    const missingItem=detectMissingItem(content);if(missingItem.matched){const intent=this.intentById.get('occurrence.missing_item');const missing=['order_reference','order_channel'].filter((field)=>!context[field]);return this.finish({intent:'occurrence.missing_item',subintent:'missing_item',entities:{item_name:{value:missingItem.item,state:missingItem.item?'provided':'missing',provenance:'message'}},origin:context.order_channel||'unknown',severity:'sensitive',fields_missing:missing,capability_id:'occurrence.create',capability_state:'degraded',authority:'A1',policy_id:'OCCURRENCE_POLICY',escalation:'E2',ideal_response:`Poxa, sinto muito que ${missingItem.item?`o ${missingItem.item}`:'um item'} não tenha chegado.`,prohibited_responses:['oferecer compensação automática'],closure:{expected_state:'open',blocked_by:['human_decision']},expected_result:{status:'unknown'},action:'record_and_escalate',legacy_blocks:intent.legacy_blocks,scenario_id:null,basis_classifications:['CANÔNICO_INTERNO'],confidence:missingItem.confidence});}
    const text=normalizeText(content);for(const[intentId,pattern,capability,severity,escalation,authority]of RULES){if(pattern.test(text)){const intent=this.intentById.get(intentId);return this.finish({intent:intentId,subintent:intentId.split('.').slice(1).join('.'),entities:{expected:intent.minimum_entities||[],values:'synthetic_or_missing_only'},origin:context.origin||'unknown',severity,fields_missing:(intent.minimum_entities||[]).filter((field)=>!context[field]),capability_id:capability,capability_state:'unknown',authority,policy_id:`policy:${intentId}`,escalation,ideal_response:null,prohibited_responses:[],closure:{expected_state:'open',blocked_by:['result:unknown']},expected_result:{status:'unknown'},action:'verify_then_continue',legacy_blocks:intent.legacy_blocks,scenario_id:null,basis_classifications:['INFERÊNCIA'],confidence:.86});}}
    const intent=this.intentById.get('conversation.ambiguous');return this.finish({intent:'conversation.ambiguous',subintent:'ambiguous',entities:{expected:[],values:'synthetic_or_missing_only'},origin:'unknown',severity:'unknown',fields_missing:['intent'],capability_id:'human.queue.create',capability_state:'unknown',authority:'A1',policy_id:'policy:conversation.ambiguous',escalation:'E1',ideal_response:'Quero entender bem antes de seguir. Qual é o assunto principal?',prohibited_responses:['inventar intenção'],closure:{expected_state:'open',blocked_by:['intent:unknown']},expected_result:{status:'unknown'},action:'clarify',legacy_blocks:intent.legacy_blocks,scenario_id:null,basis_classifications:['INFERÊNCIA'],confidence:.2});}
  finish(classification){const policies={food_safety:foodSafetyPolicy(classification,classification.ideal_response||''),abuse:classification.intent==='abuse.review'?abuseReview({}):null};return deepFreeze({...classification,schema_version:'conversation-native-classification-v1',synthetic:true,legacy_projection:legacyProjection(classification),policies});}
}

module.exports={normalizeText,RULES,extractPartyCandidates,NativeConversationEngine};
