'use strict';

const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {NativeConversationRuntime}=require('./runtime');
const {sha256,canonicalJson}=require('./deterministic');

function runScenarioIsolated(scenarioId,options={}){const runtimeRoot=fs.mkdtempSync(path.join(os.tmpdir(),'deliveryos-native-scenario-'));try{const runtime=new NativeConversationRuntime({...options,runtimeRoot});const canonical=runtime.catalogs.scenarios.scenarios.find((item)=>item.scenario_id===scenarioId);const result=runtime.runScenario(scenarioId);const snapshot=runtime.snapshot();const passed=result.classification.intent===canonical.intent&&result.classification.capability_id===canonical.capability_required&&result.result.status===canonical.expected_result.status&&result.classification.authority===canonical.authority&&result.classification.action===canonical.action&&result.closure.expected_state===canonical.closure.expected_state;const report={scenario_id:scenarioId,seed:runtime.seed,clock:runtime.clock.iso(),intent:result.classification.intent,capability:result.classification.capability_id,driver:result.route.driver_id,result:result.result.status,expected_result:canonical.expected_result.status,authority:result.classification.authority,action:result.classification.action,crm_state:runtime.crm.projectCase(result.case_id).state,handoff:result.handoff?.status||null,closure:result.closure.expected_state,passed,external_system_accessed:false,real_driver_used:false,raw_message_persisted:false,snapshot_hash:snapshot.snapshot_hash,synthetic:true};return Object.freeze({...report,report_hash:sha256(canonicalJson(report))});}finally{fs.rmSync(runtimeRoot,{recursive:true,force:true});}}

function runAllCanonicalScenarios(options={}){const probeRoot=fs.mkdtempSync(path.join(os.tmpdir(),'deliveryos-native-catalog-probe-'));const probe=new NativeConversationRuntime({...options,runtimeRoot:probeRoot});const ids=probe.catalogs.scenarios.scenarios.map((item)=>item.scenario_id);fs.rmSync(probeRoot,{recursive:true,force:true});const reports=ids.map((id)=>runScenarioIsolated(id,options));const failed=reports.filter((item)=>!item.passed).length;const summary={schema_version:'conversation-native-scenario-run-v1',synthetic:true,seed:'TATA-SIM-V1',total:reports.length,passed:reports.length-failed,failed,intents:new Set(reports.map((item)=>item.intent)).size,capabilities:new Set(reports.map((item)=>item.capability)).size,real_driver_used:reports.some((item)=>item.real_driver_used),external_system_accessed:reports.some((item)=>item.external_system_accessed),report_hash:sha256(canonicalJson(reports))};return Object.freeze({summary,reports:Object.freeze(reports)});}

module.exports={runScenarioIsolated,runAllCanonicalScenarios};
