"use strict";
const assert = require("node:assert/strict");
const { archivedResult, partiallyKnownResult, smoke } = require("./verificar_real_order_tickets_v46.js");
const {
 renderOperationalTicketsProofV46,
 renderConferenceTicketProofV46,
 renderProductionTicketProofV46,
}=require("../dist/src/production/operationalTicketEscposV46.js");

const checks=[];
function test(name, fn) {fn();checks.push(name);}

smoke();
const real=archivedResult();
const proofs=renderOperationalTicketsProofV46(real);
const conference=proofs.conference;

test("actual archived sale routes two production and one conference",()=>{
 assert.equal(proofs.production.length,2);
 assert.equal(conference.ready_for_offline_preview,true);
 assert.equal(conference.ready_for_operational_print,false);
 assert.ok(proofs.production.every(p=>p.ready_for_offline_preview));
});
test("all six physical boxes and every box operator on thermal trace",()=>{
 for(let i=1;i<=6;i++)assert.ok(conference.text_trace.includes("C"+i+"  CAIXA "));
 assert.equal((conference.text_trace.match(/Op\. ________/g)||[]).length,6);
});
test("historic order one external G and four reference-only kits",()=>{
 assert.ok(conference.text_trace.includes("1 SACOLA G"));
 assert.ok(conference.text_trace.includes("3 KIT KIDS"));
 assert.ok(conference.text_trace.includes("1 KIT QUENTE"));
 assert.ok(!/HASHI|SHOYU|GUARDANAPO/.test(conference.text_trace));
});
test("original item amounts are not interpreted as pieces",()=>{
 assert.equal((conference.text_trace.match(/1  COMBINADO KIDS/g)||[]).length,3);
 assert.ok(conference.text_trace.includes("1  EDAMAME"));
 assert.ok(conference.text_trace.includes("1  NASU NO MISSO"));
 assert.ok(conference.text_trace.includes("1  SUSHI DE UNAGUI"));
});
test("Sushi ESC/POS exposes three distinct physical boxes matching Figma and Conference",()=>{
 const sushi=proofs.production.find(p=>p.name.includes("BALCAOSUSHI1"));
 assert.ok(sushi, "historical sushi station is required");
 for(let i=1;i<=3;i++)assert.ok(sushi.text_trace.includes("C"+i+"  CAIXA 750"));
 assert.ok(sushi.text_trace.includes("C4  CAIXA 240"));
 assert.equal((sushi.text_trace.match(/1  COMBINADO KIDS/g)||[]).length,3);
 assert.ok(!sushi.text_trace.includes("3X CAIXA 750"));
 assert.ok(!sushi.text_trace.includes("3  COMBINADO KIDS"));
});
test("shared header and sequence survive without inventing new ids",()=>{
 assert.ok(conference.text_trace.includes("IFOOD 9627 | TEKNISA 0000348850"));
 assert.equal(conference.text_trace.trimEnd().split("\n").slice(-1)[0],"001");
});
test("all thermal item lines stay single-line in text mode",()=>{
 for(const p of [...proofs.production,conference]){
  assert.ok(p.text_trace.split("\n").every(line=>line.length<=64));
  assert.ok(p.byte_count>0);
 }
});
test("none of the generated byte buffers contain ESC/POS cut",()=>{
 for(const p of [...proofs.production,conference]){
  for(let i=0;i<p.bytes.length-1;i++){
   assert.ok(!(p.bytes[i]===0x1d && p.bytes[i+1]===0x56),"Cut command prohibited");
  }
  assert.deepEqual(p.effects,{print:false,spooler_write:false,odhen_write:false,cut:false});
 }
});
test("no unproven wasabi/tare/gari or cold finishing printed",()=>{
 assert.ok(!conference.text_trace.includes("ACOMP"));
 assert.ok(proofs.production.every(p=>!p.text_trace.includes("FINALIZAR:")));
});
test("incomplete real order blocks printer-ready output rather than guessing",()=>{
 const missing=renderOperationalTicketsProofV46(partiallyKnownResult()).conference;
 assert.equal(missing.ready_for_offline_preview,false);
 assert.equal(missing.bytes.length,0);
 assert.ok(missing.blocking_reasons.includes("SOURCE_IDENTIFIERS_UNPROVEN"));
 assert.ok(missing.text_trace.includes("EMBALAGEM A CONFERIR"));
 assert.ok(missing.text_trace.includes("SACOLA: A CONFERIR"));
});
test("long item refuses one-line overflow with zero bytes",()=>{
 const copy=structuredClone(real.conference);
 copy.boxes[0].items[0].print_name="PRODUTO ".repeat(20);
 const p=renderConferenceTicketProofV46(copy);
 assert.equal(p.ready_for_offline_preview,false);
 assert.equal(p.bytes.length,0);
 assert.ok(p.blocking_reasons.some(x=>x.startsWith("LINE_EXCEEDS_64_COLUMNS:ITEM")));
});
test("unrepresentable characters are blocked instead of destroyed",()=>{
 const copy=structuredClone(real.production[0]);
 copy.boxes[0].items[0].print_name="TEMPURÁ 🍣";
 const p=renderProductionTicketProofV46(copy);
 assert.equal(p.bytes.length,0);
 assert.ok(p.blocking_reasons.some(x=>x.startsWith("CHARACTER_ENCODING_UNVERIFIED:ITEM")));
});
console.log("operational-escpos-v46: "+checks.length+" local proof checks PASS");
checks.forEach(x=>console.log(" PASS "+x));
